arduino-cli_path: "D:/_dev/_Projects/dev-boards/Arduino/arduino-cli.exe"

    
connections:
  - id: &arduino-c9-115200 "arduino-c9-115200"
    compiler: "arduino-cli"
    port: "COM9"
    baudrate: 115200

devices:
  - id: &esp32-s3 "esp32-s3"
    board_model: "esp32-s3"
    fbqn: "esp32:esp32:esp32s3"    
    
mqtt:
  - id: &univ-win "univ-win"
    host: "Acer-Lappy"
    port: 1883
    username: "mqtt"
    password: "mqtt"
    
sketches:
  - id: sht21-Win
    path: "D:/_dev/_Projects/dev-boards/projects/esp32-s3__LB-Gold/sht21-solo/sht21-Win.ino"
    connection: *arduino-c9-115200
    device: *esp32-s3
    mqtt: *univ-win
    
  - id: sk6822-solo
    path: "D:/_dev/_Projects/dev-boards/projects/esp32-s3__LB-Gold/sk6822-solo/sk6822-solo.ino"
    connection: *arduino-c9-115200
    device: *esp32-s3
    mqtt: *univ-win